import { NextRequest, NextResponse } from 'next/server';

type Contract = { symbol:string; type:'call'|'put'; strike:number; expiration:string; dte:number; bid:number; ask:number; mid:number; iv:number; delta:number; gamma:number; theta:number; vega:number; volume:number; open_interest:number; score?:number };

function erf(x:number){const s=x>=0?1:-1;x=Math.abs(x);const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*x);return s*(1-(((((a5*t+a4)*t)+a3)*t+a2)*t+a1)*t*Math.exp(-x*x))}
function norm(x:number){return .5*(1+erf(x/Math.sqrt(2)))}
function pdf(x:number){return Math.exp(-.5*x*x)/Math.sqrt(2*Math.PI)}
function greeks(S:number,K:number,T:number,iv:number,type:'call'|'put'){const r=.05,s=Math.max(iv,.05),t=Math.max(T,1/365);const d1=(Math.log(S/K)+(r+.5*s*s)*t)/(s*Math.sqrt(t));const d2=d1-s*Math.sqrt(t);const delta=type==='call'?norm(d1):norm(d1)-1;const gamma=pdf(d1)/(S*s*Math.sqrt(t));const vega=S*pdf(d1)*Math.sqrt(t)/100;const theta=(-(S*pdf(d1)*s)/(2*Math.sqrt(t))-(type==='call'?r*K*Math.exp(-r*t)*norm(d2):-r*K*Math.exp(-r*t)*norm(-d2)))/365;return{delta:+delta.toFixed(2),gamma:+gamma.toFixed(4),theta:+theta.toFixed(3),vega:+vega.toFixed(3)}}
function classifyIv(r:number,p:number){const a=(r+p)/2;if(a<25)return'LOW';if(a<55)return'MEDIUM';if(a<75)return'HIGH';return'EXTREME'}
function spread(c:Contract){return c.mid<=0?999:((c.ask-c.bid)/c.mid)*100}
function liq(c:Contract){let s=0;if(c.open_interest>=1000)s+=35;if(c.volume>=300)s+=30;if(spread(c)<=18)s+=25;if(Math.abs(c.delta)>=.35)s+=10;return Math.min(s,100)}
function rank(cs:Contract[],fast:boolean){return cs.map(c=>{let score=liq(c);if(fast){if(Math.abs(c.delta)>=.35&&Math.abs(c.delta)<=.75)score+=25;if(c.dte<=45)score+=10}if(c.ask<=0||c.bid<0)score-=20;if(spread(c)>35)score-=35;return{...c,score}}).sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,10)}
function strategies(cs:Contract[],r:number,p:number,dte:number,fast:boolean){const st=classifyIv(r,p),top=rank(cs,fast),near=dte<=30,out:any[]=[];if((st==='LOW'||st==='MEDIUM')&&near)out.push({name:'Long Call / Long Put near ATM',score:fast?86:76,bias:'Directional / IV expansion',why:['IV ليس مرتفعاً جداً مقارنة بالسابق.','قرب الحدث أو الانتهاء قد يدعم حركة سريعة.','Fast Profit Mode يفضل Delta أعلى وStrike قريب.'],risks:['Theta يضغط العقد إذا لم يتحرك الأصل.','IV Crush بعد الحدث قد يضر العقد.'],preferred_contracts:top.slice(0,2).map(c=>c.symbol)});if(st==='MEDIUM'||st==='HIGH')out.push({name:'Credit Vertical Spread',score:78,bias:'Income / Defined risk',why:['IV متوسط أو مرتفع يعطي Premium أفضل.','المخاطرة محددة مقارنة ببيع عقد عاري.','Theta غالباً لصالح الصفقة.'],risks:['الربح محدود.','الحركة القوية ضد السبريد ترفع الخسارة.'],preferred_contracts:top.slice(0,4).map(c=>c.symbol)});if(near&&(st==='MEDIUM'||st==='HIGH'))out.push({name:'Strangle / Straddle',score:73,bias:'Volatility movement',why:['مفيد إذا الاتجاه غير واضح لكن الحركة متوقعة.','يقيس فرصة الاستفادة من توسع الحركة.'],risks:['يحتاج حركة كبيرة لتغطية تكلفة العقدين.','IV Crush بعد الحدث خطر.'],preferred_contracts:top.slice(0,4).map(c=>c.symbol)});return out.sort((a,b)=>b.score-a.score).slice(0,3)}
async function finnhubPrice(ticker:string){const key=process.env.FINNHUB_API_KEY||process.env.NEXT_PUBLIC_FINNHUB_API_KEY;if(!key)throw new Error('NO_KEY');const url=`https://finnhub.io/api/v1/quote?symbol=${encodeURIComponent(ticker)}&token=${key}`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('HTTP_'+res.status);const data=await res.json();if(!data||!data.c||Number(data.c)<=0)throw new Error('NO_PRICE');return Number(data.c)}
function estimatedMarket(ticker:string,S:number,source:string){ticker=ticker.toUpperCase();const exp=new Date(Date.now()+24*86400000).toISOString().slice(0,10),dte=24;const strikes=[Math.round(S*.94),Math.round(S*.97),Math.round(S),Math.round(S*1.03),Math.round(S*1.06)];const contracts:Contract[]=[];const baseIv=ticker==='SPY'?.22:ticker==='AAPL'?.28:ticker==='NVDA'?.55:ticker==='TSLA'?.48:.35;const ivRank=Math.round(baseIv*100),ivPercentile=Math.min(95,ivRank+10);for(const K of strikes){for(const type of ['call','put'] as const){const near=Math.max(.05,1-Math.abs(K-S)/S*8),mid=Math.max(.35,S*(type==='call'?.030:.028)*near*baseIv/.35),iv=type==='call'?baseIv:baseIv*1.05,g=greeks(S,K,dte/365,iv,type);contracts.push({symbol:`${ticker}_${exp}_${K}${type==='call'?'C':'P'}`,type,strike:K,expiration:exp,dte,bid:+(mid*.96).toFixed(2),ask:+(mid*1.04).toFixed(2),mid:+mid.toFixed(2),iv,...g,volume:Math.round((type==='call'?2500:2100)*near+100),open_interest:Math.round((type==='call'?9000:8200)*near+450)})}}return{ticker,underlying_price:+S.toFixed(2),expiration:exp,dte,iv_rank:ivRank,iv_percentile:ivPercentile,contracts,source}}
export async function GET(req:NextRequest,{params}:{params:{ticker:string}}){const fast=req.nextUrl.searchParams.get('fastProfit')!=='false';let m:any;const notes:string[]=[];try{const S=await finnhubPrice(params.ticker.toUpperCase());m=estimatedMarket(params.ticker,S,'FINNHUB LIVE PRICE + ESTIMATED OPTIONS');notes.push('تم جلب السعر الحي من Finnhub. بيانات الأوبشن/Greeks حالياً تقديرية حتى نربط مزود Options متخصص.')}catch(e){const fallback:any={TSLA:178.5,NVDA:945.2,SPY:529.1,QQQ:451.3,AAPL:190.15};m=estimatedMarket(params.ticker,fallback[params.ticker.toUpperCase()]??250,'DEMO FALLBACK');notes.push('لم يتم جلب Finnhub. تأكد من FINNHUB_API_KEY ثم أعد Redeploy.')}if(fast)notes.push('Fast Profit Mode مفعل: يفضل ATM / Near ITM وDelta أعلى.');const top=rank(m.contracts,fast);const expected=+(m.underlying_price*(top[0]?.iv||.4)*Math.sqrt(m.dte/365)).toFixed(2);return NextResponse.json({ticker:m.ticker,underlying_price:m.underlying_price,iv_state:classifyIv(m.iv_rank,m.iv_percentile),iv_rank:m.iv_rank,iv_percentile:m.iv_percentile,expiration:m.expiration,dte:m.dte,expected_move:expected,source:m.source,market_notes:notes,top_contracts:top,strategies:strategies(m.contracts,m.iv_rank,m.iv_percentile,m.dte,fast)})}
